// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    //apiKey: 'AIzaSyA7fwt3GJ5NFfutpUXP-cRmaeJ_hNwabfE', //lama
    apiKey: 'AIzaSyDcfYEvu3hRWG7KUTk4V9sWT6YDsiJ5w2I',
    appId: '1:222554583729:web:56f76d95a5b1f0f9cfe890',
    messagingSenderId: '222554583729',
    projectId: 'tubes-ppb-f1ddc',
    authDomain: 'tubes-ppb-f1ddc.firebaseapp.com',
    storageBucket: 'tubes-ppb-f1ddc.firebasestorage.app',
    measurementId: 'G-V7PNTKE61W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    //apiKey: 'AIzaSyAWXm1NsjZYdAFNAjxYPqioM1FZK1StJ98', //lama
    apiKey: 'AIzaSyCyLP-4dLUINzS9ZWQBXRb2V-bFyGnrzmw',
    appId: '1:222554583729:android:2ef1243286d645adcfe890',
    messagingSenderId: '222554583729',
    projectId: 'tubes-ppb-f1ddc',
    storageBucket: 'tubes-ppb-f1ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    //apiKey: 'AIzaSyDtk4IcGAmeM9gvqFxIAa19yHK5YByyy2g', //lama
    apiKey: 'AIzaSyDMEa0ys40DfIjFaehX8zzJXHyp4UFpsJ8',
    appId: '1:222554583729:ios:7ff78f5d0bc44b0bcfe890',
    messagingSenderId: '222554583729',
    projectId: 'tubes-ppb-f1ddc',
    storageBucket: 'tubes-ppb-f1ddc.firebasestorage.app',
    androidClientId: '222554583729-ot545mikardh7vtb3kbn0kev1di88des.apps.googleusercontent.com',
    iosClientId: '222554583729-36f4c3hoepmjfa6ibms214ftitk4lb6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesPpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtk4IcGAmeM9gvqFxIAa19yHK5YByyy2g',
    appId: '1:222554583729:ios:7ff78f5d0bc44b0bcfe890',
    messagingSenderId: '222554583729',
    projectId: 'tubes-ppb-f1ddc',
    storageBucket: 'tubes-ppb-f1ddc.firebasestorage.app',
    androidClientId: '222554583729-ot545mikardh7vtb3kbn0kev1di88des.apps.googleusercontent.com',
    iosClientId: '222554583729-36f4c3hoepmjfa6ibms214ftitk4lb6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesPpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7fwt3GJ5NFfutpUXP-cRmaeJ_hNwabfE',
    appId: '1:222554583729:web:1321d6b4f254fee8cfe890',
    messagingSenderId: '222554583729',
    projectId: 'tubes-ppb-f1ddc',
    authDomain: 'tubes-ppb-f1ddc.firebaseapp.com',
    storageBucket: 'tubes-ppb-f1ddc.firebasestorage.app',
    measurementId: 'G-73V183SF7T',
  );
}
